---
- name: Get old UUID
  vmware_guest_info:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    name: "{{ vs_template }}"
  delegate_to: localhost
  register: oldvm_facts
  tags: [ uuid, olduuid ]
- debug:
    msg: "{{ oldvm_facts.instance.instance_uuid }}"
  tags: always
