---
- name: Get latest UUID
  vmware_guest_info:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    name: "{{ inventory_hostname }}"
  delegate_to: localhost
  register: latestvm_facts
  tags: [ uuid, newuuid ]
- name: Print latest uuid
  debug:
    msg: "{{ latestvm_facts.instance.instance_uuid }}"
  tags: always
