---
- name: Get old UUID
  vmware_guest_info:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    name: "{{ vs_template }}"
    schema: "vsphere"
    properties:
      - instance_uuid
  delegate_to: localhost
  register: oldtemplate_uuid_info
  tags: [ uuid, olduuid ]