---
- name: Rename new Latest
  vmware_guest: 
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    datastore: "{{ vs_datastore }}"
    uuid: "{{ newvm_uuid_info }}"
    name: "{{vs_os}}_latest"
    state: present
  delegate_to: localhost
  tags: [ rename, renamelatest ]