---
- name: Rename old template
  vars:
    name_date: "{{ lookup('pipe','date +%Y_%m') }}"
  vmware_guest: 
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    datastore: "{{ vs_datastore }}"
    cluster: "{{ vs_cluster }}"
    folder: "/{{ vs_datacenter }}/{{ vs_folder }}"
    uuid: "{{ oldvm_facts.instance.instance_uuid }}"
    name: "{{vs_os}}-{{ name_date }}"
    state: present
  delegate_to: localhost
  tags: [rename, renameold ]