---
- name: convert old to VM # Usign PWSH script
    shell: /usr/bin/pwsh files/rename.ps1 {{ vs_hostname }}  {{ vs_name }} {{ vs_password }} {{ vs_template }} {{vs_os}}-{{ name_date }}
  delegate_to: localhost
  tags: [rename, renameold]