---
- name: Power off VM
  vmware_guest_powerstate: 
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    name: "{{ inventory_hostname }}"
    state: shutdown-guest
    state_change_timeout: 200
  delegate_to: localhost
  tags: shutdown