---
- name: Transfer update file
  vmware_guest_file_operation:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    vm_username: "{{ vm_username }}"
    vm_password: "{{ vm_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    vm_id: "{{ inventory_hostname }}"
    copy: 
      src: files/update.sh
      dest: /root/update.sh
  delegate_to: localhost
  register: result
  tags: transfer

- name: transfer Output
  debug:
    var: result 
    verbosity: 2