---
- name: Transfer update file
  vmware_guest_file_operation:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    vm_username: "{{ vm_username }}"
    vm_password: "{{ vm_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    vm_id: "{{ inventory_hostname }}"
    copy: 
      src: files/update.sh
      dest: /root/update.sh
  delegate_to: localhost
  register: result
  tags: transfer
- name: transfer Output
  debug:
    var: result 
    verbosity: 2
- name: Chmod update file
  vmware_vm_shell:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    datacenter: "{{ vs_datacenter }}"
    folder: "/{{ vs_datacenter }}/{{ vs_folder }}"
    vm_id: "{{ inventory_hostname }}"
    vm_username: "{{ vm_username }}"
    vm_password: "{{ vm_password }}"
    vm_shell: "/bin/chmod"
    vm_shell_args: "+x /root/update.sh"
    wait_for_process: True
    timeout: 3600                    #3600 seconds is default
  register: shell_command
  delegate_to: localhost
  tags: [ transfer, chmod ]
- name: Transfer sysprep file
  vmware_guest_file_operation:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    vm_username: "{{ vm_username }}"
    vm_password: "{{ vm_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    vm_id: "{{ inventory_hostname }}"
    copy: 
      src: files/sysprep.sh
      dest: /root/sysprep.sh
  delegate_to: localhost
  register: sysxfer_result
  tags: transfer