---
- name: Transfer update file
  vmware_guest_file_operation:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    vm_id: "{{ inventory_name }}"
    copy: 
      src: files/update.sh
      dest: /root/update.sh
    delegate_to: localhost
