---
- name: Update notes
  vars:
    name_date: "{{ lookup('pipe','date +%Y-%m') }}"
  vmware_guest: 
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    datacenter: "{{ vs_datacenter }}"
    datastore: "{{ vs_datastore }}"
    folder: "/{{ vs_datacenter }}/{{ vs_folder }}"
    uuid: "{{ latestvm_facts.instance.instance_uuid }}"
    annotation: "Updated: {{ name_date }} "
    state: present
  delegate_to: localhost
  tags: notes
