---
- name: Update notes
  vars:
    name_date: "{{ lookup('pipe','date +%Y-%m') }}"
  vmware_guest: 
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    validate_certs: no
    name: "{{ inventory_hostname }}"
    annotation: "{{ VM_notes}}\nUpdated: {{ name_date }} "
    state: present
  delegate_to: localhost
  tags: notes
