---
- name: Update VM 
  vmware_vm_shell:
    hostname: "{{ vs_hostname }}"
    username: "{{ vs_name }}"
    password: "{{ vs_password }}"
    datacenter: "{{ vs_datacenter }}"
    folder: "/{{ vs_datacenter }}/{{ vs_folder }}"
    vm_id: "{{ inventory_hostname }}"
    vm_username: "{{ vm_username }}"
    vm_password: "{{ vm_password }}"
    vm_shell: /root/update.sh
    wait_for_process: True
    timeout: 3600                    #3600 seconds is default
  register: shell_command
  delegate_to: localhost
  tags: update
- name: remove satreg # Using local shell script
  shell: files/sat_remove.sh "{{ inventory_hostname }}" "(( sat_user }}" "{{ sat_passwd | quote }}"
  delegate_to: localhost
  tags: [update, satremove]